"""Initial migration.

Revision ID: 82266f0d78ce
Revises: 
Create Date: 2022-01-13 22:42:54.386216

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '82266f0d78ce'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('araba', sa.Column('durum2', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('araba', 'durum2')
    # ### end Alembic commands ###
